POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "eu@email.com",
    "password": "123456"
}

###
POST http://localhost:3003/signup
Content-Type: application/json

{
    "username": "Flamarion",
    "email": "eu@email.com",
    "password": "123456",
    "confirmPass": "123456",
    "role": "ADM"
}

###
GET http://localhost:3003/contracts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNWYxYzE5ZTMtZTQzMi00NGZlLThhNzUtZTc5ODAzZDBiZGI2IiwiaWF0IjoxNjg5NTY3Nzg4LCJleHAiOjE2ODk1NzEzODh9.pT-pDnOAdd-rp9ItB9UIdVYlZhPIg-14btfT3wb8vGE